### Get the current inventory
GET http://localhost:3002/api/v1/inventory

### Delete the current inventory
DELETE http://localhost:3002/api/v1/inventory

### Restock inventory
POST http://localhost:3002/api/v1/inventory/restock

### Submit a simple order
// @name wfrequest
POST http://localhost:3006/orders
Content-Type: application/json

{"customer": "kendall", "item": "orange", "total": 100}

### Submit an expensive order
// @name wfrequest_approval
POST http://localhost:3006/orders
Content-Type: application/json

{"customer": "Veronica", "item": "kiwi", "total": 1299.00}

### Get the status of an order
@instance_id = {{wfrequest.response.body.instance_id}}

GET http://localhost:3006/orders/{{instance_id}}

### Approve an order
@instance_id = {{wfrequest_approval.response.body.instance_id}}

POST http://localhost:3006/orders/{{instance_id}}/approve
Content-Type: application/json

{"approver": "kendall", "approved": true}


