### Get the current inventory
GET http://localhost:3002/inventory

### Delete the current inventory
DELETE http://localhost:3002/inventory

### Restock
POST http://localhost:3002/inventory/restock

### Reserve
POST http://localhost:3002/inventory/reserve

### Submit a payment
POST http://localhost:3003/payments/charge
Content-Type: application/json

{"id": "test", "customer": "bob", "items": ["oranges"], "total": 12.00}

### Submit a simple order
POST http://localhost:3000/orders
Content-Type: application/json

{"customer": "bob", "items": ["kiwi"], "total": 12.00}

### Submit an expensive order
POST http://localhost:3000/orders
Content-Type: application/json

{"customer": "Cecilia", "items": ["kiwi"], "total": 1299.00}


### Get the status of an order
GET http://localhost:3000/orders/order_bob_2n3yd


### Approve an order
POST http://localhost:3000/orders/order_cecilia_e83nq/approve
Content-Type: application/json

{"approver": "Kendall", "approved": true}


