apiVersion: cra.diagrid.io/v1beta1
kind: Component
metadata:
  name: square-api
spec:
  type: bindings.http
  version: v1
  metadata:
    - name: url
      value: https://connect.squareupsandbox.com/
    - name: securityToken
      value: Bearer EAAAlxbliuWPW7357cx_imTWI952FaGmXwFk__Yq-WbV4XtFNWielHbztx7B-itx
    - name: securityTokenHeader
      value: Authorization
  scopes:
    - payments
